### ISSUE TITLE
Package doesn't build on Python >= 3.11 due to betaincder.h missing

### ISSUE THREAD

**Issue by ocramz** [canerturkmen/betaincder#3]
> source venv/bin/activate && pip install betaincder 2>&1 | tail -20

```
copying betaincder/c/digamma.c -> build/lib.linux-x86_64-cpython-311/betaincder/c
copying betaincder/c/beta.c -> build/lib.linux-x86_64-cpython-311/betaincder/c
running build_ext
building 'betaincder.c.betaincder' extension
creating build/temp.linux-x86_64-cpython-311/betaincder/c
x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -fPIC -I/workspaces/topopt-irg-beta/venv/include -I/usr/include/python3.11 -c betaincder/c/betaincder.c -o build/temp.linux-x86_64-cpython-311/betaincder/c/betaincder.o -O3 -march=native -std=c99
betaincder/c/betaincder.c:207:12: fatal error: longintrepr.h: No such file or directory
  207 |   #include "longintrepr.h"
      |            ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]
```
